objects = master porto nave meteo
all: $(objects)

launchMaster:
	./master

launchNave:
	./nave

launchPorto:
	./porto

launchMeteo:
	./meteo

clean:
	rm -f porto nave master utility meteo a.out

master:
	cc -D_GNU_SOURCE -std=c89 -Wpedantic utility.c master.c -o master

nave:
	cc -D_GNU_SOURCE -std=c89 -Wpedantic utility.c nave.c -nostartfiles -e startNave -o nave

porto:
	cc  -D_GNU_SOURCE -std=c89 -Wpedantic utility.c porto.c -nostartfiles -e startPorto -o porto

meteo:
	cc -D_GNU_SOURCE -std=c89 -Wpedantic utility.c meteo.c -nostartfiles -e startMeteo -o meteo

